[globals]
sample_size = 5
output_directory = "demo-result"
extra_perf_events = ["cpu-clock"]
debug = false
deep_trace = true

# cpu bound benchmark
[[tasks]]
executable = "examples/nbody/nbodySim"
args = ["10000000"]
enclave_size = ["1G"]

# i/o bound benchmark
[[tasks]]
executable = "/usr/bin/bonnie++"
args = ["-d", "{{ output_directory }}", "-q", "-u", "giuseppe", "-r", "{{ ram_size }}"]
storage_type = ["encrypted", "untrusted"]
enclave_size = ["512M"]

post_run_executable = "rm"
post_run_args = ["-rf", "{{ output_directory }}/Bonnie.*"]
