[globals]
sample_size = 5
output_directory = "demo-result"
extra_perf_events = ["cpu-clock"]
debug = false
deep_trace = true

# cpu bound benchmark
[[tasks]]
executable = "examples/nbody/nbodySim"
args = ["10000000"]

# i/o bound benchmark
[[tasks]]
executable = "/usr/bin/bonnie++"
args = ["-d", "{{ output_directory }}", "-q", "-u", "giuseppe"]
storage_type = ["encrypted", "untrusted"]
num_threads = [1, 2, 4]

post_run_executable = "rm"
post_run_args = ["-r", "{{ output_directory }}/*"]
