[globals]
sample_size = 3
enclave_size = ["64M", "128M"]
output_directory = "/tmp/test"
num_threads = [1, 2]
extra_perf_events = ["cpu-clock"]
energy_sample_interval = "250ms"
debug = true

[[tasks]]
executable = "/bin/dd"
args = ["if=/dev/zero", "of=/dev/null", "count=10000"]

[[tasks]]
pre_run_executable = "/usr/bin/echo"
pre_run_args = ["Starting make"]

executable = "/usr/bin/make"
args = ["-C", "examples/basic-c-app/", "-j", "{{ num_threads }}", "app", "output={{ output_directory }}"]

post_run_executable = "/usr/bin/make"
post_run_args = ["-C", "examples/basic-c-app", "clean", "output={{ output_directory }}"]

[[tasks]]
executable = "examples/simple-writer/writer"
args = ["{{ output_directory }}"]
storage_type = ["encrypted", "tmpfs", "untrusted"]

