[globals]
sample_size = 1
enclave_size = ["256M"]
output_directory = "test"
num_threads = [1]
extra_perf_events = ["cpu-clock"]
debug = false
trace = false

[[tasks]]
executable = "/bin/dd"
args = ["if=/dev/zero", "of={{ output_directory }}/a.zero", "count=1000000"]
storage_type = ["encrypted", "tmpfs", "untrusted"]
