[globals]
sample_size = 1
epc_size = ["64M"]
output_directory = "test"
num_threads = [1]
extra_perf_events = ["cpu-clock"]

[[tasks]]
executable = "/bin/dd"
args = ["if=/dev/zero", "of={{ output_directory }}/a.zero", "count=10000000"]
