[globals]
sample_size = 1
output_directory = "test"
extra_perf_events = ["cpu-clock"]
debug = false
deep_trace = false

[[tasks]]
executable = "/bin/dd"
args = ["if=/dev/zero", "of={{ output_directory }}/a.zero", "count=100000"]
storage_type = ["encrypted", "untrusted"]
enclave_size = ["256M"]
