[globals]
sample_size = 3
output_directory = "/tmp/test"
extra_perf_events = ["cpu-clock"]

[[tasks]]
pre_run_executable = "/usr/bin/echo"
pre_run_args = ["Start task"]

executable = "/bin/dd"
args = ["if=/dev/zero", "of=/dev/null", "count=10000"]
enclave_size = ["64M"]

post_run_executable = "/usr/bin/echo"
post_run_args = ["End task"]

[[tasks]]
executable = "/usr/bin/sleep"
args = ["1"]
enclave_size = ["64M"]
