name: "Sphinx: Render docs"

on: 
  push:
    # paths:
    #   - docs/web/

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: actions/setup-python@v5
      with:
        cache: pip
    - name: Install dependencies
      run: |
          DEBIAN_FRONTEND=noninteractive apt-get-install -y make
          pip install -r requirements.txt 
    - name: Sphinx Build HTML
      run: make -C docs/web html
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/web/build/html/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/web/build/html

