name: Create release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: docs/report-ita/main.tex

      - name: Build LaTeX document
        run: |
          latexmk -pdf -output-directory=docs/report-ita/build -cd docs/report-ita/main.tex
          cp docs/report-ita/build/main.pdf docs/report-ita/build/[ITA]-Report.pdf

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes \
              docs/report-ita/build/[ITA]-Report.pdf
