name: Rust

on:
  push:
    branches: [ "main"]
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Build
      run: cargo build --verbose

  test:
    name: test
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - uses: actions/cache@v4
      id: cache-docker-image
      with:
        path: /tmp/.docker-cache
        key: ${{ runner.os }}-${{ hashFiles('Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: Load Docker image from cache
      if: steps.cache-docker-image.outputs.cache-hit == 'true'
      run: |
        docker load -i /tmp/.docker-cache/gramine-sdk.tar

    - name: Build Docker image
      if: steps.cache-docker-image.outputs.cache-hit != 'true'
      run: |
        docker build -t gramine-sdk .
        mkdir -p /tmp/.docker-cache
        docker save gramine-sdk -o /tmp/.docker-cache/gramine-sdk.tar

    - name: Run tests
      run: docker run --privileged -v $(pwd):/workspace/benchmark -w /workspace/benchmark gramine-sdk cargo test --verbose
